name: at_a_look_diary
description: 한 눈에 보는 일기장
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
<<<<<<< HEAD
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_database: ^11.1.4
  firebase_storage: ^12.3.4
=======
  firebase_core: ^3.8.0
  firebase_auth: ^5.4.0
  firebase_database: ^11.1.4
  firebase_storage: ^12.3.3
  cloud_firestore: ^5.4.4
>>>>>>> abbc0af (Refactor: Firestore user mode & couple base setup)

  # Google 로그인
  google_sign_in: ^6.2.1

  # UI
  table_calendar: ^3.0.9

  # 이미지
  image_picker: ^1.0.7

  # 유틸리티
  intl: ^0.18.1
<<<<<<< HEAD
  # 공유 기능
  share_plus: ^7.2.1
=======

  # 공유 기능
  share_plus: ^7.2.2
>>>>>>> abbc0af (Refactor: Firestore user mode & couple base setup)

  # URL 런처
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # 폰트
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700




  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
